# Generated by Django 5.0.6 on 2024-06-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_author_alter_playlist_songs'),
        ('songs', '0012_alter_songmodel_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='songs.songmodel'),
        ),
    ]
