# Generated by Django 5.0.6 on 2024-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
