# Generated by Django 5.0.6 on 2024-06-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_playlist_song_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_text',
        ),
    ]
